import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Header from "../components/ui/Header";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={playfair.className}>
        <Header />
        <main>{children}</main>
        <footer className="bg-[#434242] text-white p-4 text-center">
          {/* 省略 */}
          <p className="text-sm">Copyright © 2025 my portfolio</p>
        </footer>
      </body>
    </html>
  );
}
